### ISSUE TITLE
About the performance under targeted attack setting

### ISSUE THREAD

**Issue by lwmming** [Trustworthy-AI-Group/PGN#3]
A very impressive work! Have you conducted the evaluation under targeted attack setting?

**Comment by Zhijin-Ge** [comment]
Hi~, Thank you for your interest in our work!  In this paper, we didn't conduct the evaluation under the targeted attack setting due to time limitations during the paper submission. But, we have performed a simple test before that, and the results verified that PGN is also effective in enhancing the transferability in targeted attacks.  For instance, in the case of ResNet-50 → Inception-v3, VMI, RAP, and PGN can achieve 1.3%, 2.4%, and 5.3% targeted attack success rates, respectively. We hope this information is useful for you! If you have any other questions, please feel free to contact me!

**Comment by lwmming** [comment]
Thank you for your reply. Where should we modify the current codes when performing under targeted attack setting?

**Comment by Zhijin-Ge** [comment]
Two pieces of code need to be modified:
1. Load the dataset to ensure that the target label is returned
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/58e5af30-74d8-4d40-bd00-e2435a97f639)

2. The difference between untargeted and targeted attacks is that the former maximizes the loss function, while the latter minimizes it. Therefore, during the iteration process, we need to adjust the sign to change from positive to negative.
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/89b7d18d-3f0a-4ca2-a96f-62365c83e0ad)

3. Additionally, we need to set the parameters as follows: $\alpha=2/255,  T=400, \epsilon=16/255$.
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/42350897/7749bbff-2e6a-49b8-98e3-7bc3d8cfa414)

**Comment by lwmming** [comment]
Thank you very much for your meticulous reply.

**Comment by Truman168** [comment]
你好，我想请问一下，如果是评估target attack，那改怎么修改verify部分的代码呀？
因为我跑出来的结果和你描述的有点差别
![image](https://github.com/Trustworthy-AI-Group/PGN/assets/144144824/ea00e634-fecd-46ab-8d9c-21b9e6e74442)

**Comment by Zhijin-Ge** [comment]
你好，你的结果应该是正确的，我当时跑这个实验的时候只是初步验证了一下有效性，迭代次数并没有跑满，所以描述的结果有些偏低。

**Comment by Truman168** [comment]
> 你好，你的结果应该是正确的，我当时跑这个实验的时候只是初步验证了一下有效性，迭代次数并没有跑满，所以描述的结果有些偏低。

好的，感谢回复！
